.PHONY: clean All

All:
	@echo "----------Building project:[ Molecule - Debug ]----------"
	@cd "Molecule" && $(MAKE) -f  "Molecule.mk"
clean:
	@echo "----------Cleaning project:[ Molecule - Debug ]----------"
	@cd "Molecule" && $(MAKE) -f  "Molecule.mk" clean
