//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/textctrl.h>
#include <wx/gauge.h>
#include <wx/button.h>

class MainDialogBaseClass : public wxDialog
{
protected:
    wxTextCtrl* m_textReport;
    wxGauge* m_gauge62;
    wxButton* m_buttonRunSim;
    wxButton* m_buttonSettings;
    wxButton* m_buttonSave;
    wxButton* m_buttonExit;

protected:

public:
    MainDialogBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("BrownianWX"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,330), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~MainDialogBaseClass();
};

#endif
