.PHONY: clean All

All:
	@echo "----------Building project:[ wxWidgetsHello - Debug ]----------"
	@$(MAKE) -f  "wxWidgetsHello.mk"
clean:
	@echo "----------Cleaning project:[ wxWidgetsHello - Debug ]----------"
	@$(MAKE) -f  "wxWidgetsHello.mk" clean
