//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainDialogBaseClass::MainDialogBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxDialog(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    wxBoxSizer* mainSizer = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(mainSizer);
    
    mainSizer->Add(0, 0, 1, wxALL|wxEXPAND, 5);
    
    m_staticTextHello = new wxStaticText(this, wxID_ANY, _("Welcome~!"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    mainSizer->Add(m_staticTextHello, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
    
    m_textCtrlHello = new wxTextCtrl(this, wxID_ANY, wxT(""), wxDefaultPosition, wxSize(-1,-1), wxTE_READONLY);
    #if wxVERSION_NUMBER >= 3000
    m_textCtrlHello->SetHint(wxT(""));
    #endif
    
    mainSizer->Add(m_textCtrlHello, 0, wxALL|wxALIGN_CENTER_HORIZONTAL|wxALIGN_CENTER_VERTICAL, 5);
    
    m_staticLine15 = new wxStaticLine(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxLI_HORIZONTAL);
    
    mainSizer->Add(m_staticLine15, 0, wxALL|wxEXPAND, 5);
    
    wxBoxSizer* boxSizer12 = new wxBoxSizer(wxHORIZONTAL);
    
    mainSizer->Add(boxSizer12, 0, wxALL|wxALIGN_CENTER_HORIZONTAL, 5);
    
    m_buttonHello = new wxButton(this, wxID_HELLO, _("Hello"), wxDefaultPosition, wxSize(-1,-1), 0);
    m_buttonHello->SetDefault();
    
    boxSizer12->Add(m_buttonHello, 0, wxALL, 5);
    
    m_buttonEXIT = new wxButton(this, wxID_EXIT, _("Exit"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer12->Add(m_buttonEXIT, 0, wxALL, 5);
    
    SetMinSize( wxSize(300,200) );
    SetSizeHints(300,200);
    if ( GetSizer() ) {
         GetSizer()->Fit(this);
    }
    Centre(wxBOTH);
    // Connect events
    m_buttonHello->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnIDHELLOClicked), NULL, this);
    m_buttonEXIT->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnIDEXITClicked), NULL, this);
    
}

MainDialogBaseClass::~MainDialogBaseClass()
{
    m_buttonHello->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnIDHELLOClicked), NULL, this);
    m_buttonEXIT->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainDialogBaseClass::OnIDEXITClicked), NULL, this);
    
}
