//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/dialog.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/textctrl.h>
#include <wx/gauge.h>
#include <wx/button.h>
#include <wx/stattext.h>

class MainDialogBaseClass : public wxDialog
{
protected:
    wxTextCtrl* m_textReport;
    wxGauge* m_gaugeCalculation;
    wxButton* m_buttonRunSim;
    wxButton* m_buttonSettings;
    wxButton* m_buttonSave;
    wxButton* m_buttonExit;

protected:
    virtual void OnInitMainDialog(wxInitDialogEvent& event) { event.Skip(); }
    virtual void OnBtnRunClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtnSettingsClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtnSaveClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtnExitClicked(wxCommandEvent& event) { event.Skip(); }

public:
    MainDialogBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("BrownianWX"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,330), long style = wxDEFAULT_DIALOG_STYLE);
    virtual ~MainDialogBaseClass();
};


class SettingsDialogBase : public wxDialog
{
protected:
    wxStaticText* m_staticTextLeft;
    wxTextCtrl* m_textCtrlLeft;
    wxStaticText* m_staticTextRight;
    wxTextCtrl* m_textCtrlRight;
    wxStaticText* m_staticTextTop;
    wxTextCtrl* m_textCtrlTop;
    wxStaticText* m_staticTextBottom;
    wxTextCtrl* m_textCtrlBottom;
    wxStaticText* m_staticTextVelXMax;
    wxTextCtrl* m_textCtrlVelXMax;
    wxStaticText* m_staticTextVelYMax;
    wxTextCtrl* m_textCtrlVelYMax;
    wxButton* m_buttonApply;
    wxButton* m_buttonClose;

protected:
    virtual void OnBtnApplyClicked(wxCommandEvent& event) { event.Skip(); }
    virtual void OnBtnCloseClicked(wxCommandEvent& event) { event.Skip(); }

public:
    SettingsDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Rect. Settings"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(280,330), long style = wxDEFAULT_DIALOG_STYLE|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~SettingsDialogBase();
};

#endif
